# Generated by Django 4.1.3 on 2022-11-15 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("women", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="women",
            name="is_published",
            field=models.BooleanField(default=True),
        ),
    ]
